### ISSUE TITLE
Hi Just want ur help on something

### ISSUE THREAD

**Issue by sid6942** [Boryyy/bory#1]
is:issue is:open hi i would like to ask you something about an instagram project i saw ur comment on ( Khanejo/Instagram-mass-reporter. )

**Comment by Boryyy** [comment]
hello , yes tell me?

**Comment by sid6942** [comment]
> hello , yes tell me?

so i was reading your closed issue Chat  can u help me configure the tool

**Comment by Boryyy** [comment]
the code was really bad i did it myself from the start , i just tried it and its not working u need to update it 

```
username = input("Username: ")

a = open('acc.txt', "r").readlines()
file = [s.rstrip()for s in a]
file.reverse()

new_file=[]
for i in range(len(file)):
    split=file[i].split(":")
    new_file.append(split[0])
    new_file.append(split[1])
    
user =[]
passw = []

for j in range(len(new_file)):
    if (j%2)==0:
        user.append(new_file[j])
    else:
        passw.append(new_file[j])
```
this line here will help u with ur problem
